development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rails_elasticsearch_development
  pool: 5

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rails_elasticsearch_test

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rails_elasticsearch_production
